# Permalinks
permalink:           pretty

# Setup
title:               4A616D6573
# tagline:             An information security and personal education blog
url:                 http://4a616d6573.com/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James
  url:               https://twitter.com/4A616D6573/
#  email:

# Custom vars
version:             1.0.0
github:              https://github.com/4A616D6573/
#   repo:

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
